version: "3.9"

services:
    nyte:
        image: meawesome/nyte:dev
        container_name: nyte
        environment:
            - MEDIA_DIRECTORY=/app/data/media
        ports:
            - "3000:3000"
        volumes:
            - nyte_dev:/app/data
        restart: unless-stopped

volumes:
    nyte_dev:
        external: true
